### ISSUE TITLE
Enhancement: Field sorting

### ISSUE THREAD

**Issue by bastibuck** [1up-lab/contao-mailchimp#6] opened 2017-08-25 13:12 UTC
Cheers,

really enjoy your extension, thanks! 
I'm using it in a Contao 3.5 and it works good.

But there is one small thing I would like to see: if I add a field in MailChimp before the email field it doesn't show up in front of the email field in my website. 

MailChimp:
![image](https://user-images.githubusercontent.com/6306291/29715141-60000ff4-89a6-11e7-862f-fed4924ecba0.png)

Website:
![image](https://user-images.githubusercontent.com/6306291/29715188-7dff1612-89a6-11e7-9754-ab58ba1718a3.png)

This is due to the code in `ModuleSucscribe.php` where you add the email field (line 59) before you go over each field (line 70) that is additionally added in MailChimp. Would be awesome if you could change the code so that it looks for the order in MailChimp and outputs it to the website as well.

If you need more info let me know.

Thanks,
bastibuck

**Comment by bastibuck** [comment] 2017-08-25 13:52
PS: For now I'm overwriting your compile() in a custom Class and reorder fields this way. If I come up with a general solution I will create a PR, but unfortunately it's not a high priority right now since it works now.

**Comment by bytehead** [comment] 2017-09-04 14:11
Nice catch. I'll try to implement/fix this.

**Comment by bezin** [comment] 2017-09-26 08:40
@bastibuck how do you even manage to add a form field before the email field? I just tried to investigate this issue and I even fail to reproduce this 8-)

**Comment by bastibuck** [comment] 2017-09-26 10:46
Hehe ;-) 

You can **not** change order in _Settings-->List fields and *|MERGE|* tags_ but you **can** in _Signup forms --> General forms --> Signup form_

The order you pick here (drag'n'drop) will also be visible in the *|MERGE|* tags view.

Hope this helps

**Comment by bezin** [comment] 2017-09-26 11:00
Indeed – that is weird, though :D Anyway, I gonna look into this.

**Comment by bytehead** [comment] 2017-09-26 11:59
In the very beginning there was only the email field. It's probably because of that. I'll check this and bring up a PR if we can change it.

**Comment by bezin** [comment] 2017-09-26 12:09
There might be another issue: the api call to "lists/$listid/merge-fields" only returns all the other fields, but not the email field. It also does not reflect the order of the fields, even though the order changes in the list fields view of the MailChimp interface…

**Comment by bytehead** [comment] 2017-09-26 12:11
> the api call to "lists/$listid/merge-fields" only returns all the other fields, but not the email field.

Ah, I remember this.

**Comment by bytehead** [comment] 2017-09-26 13:23
So this will basically be a known limitation?

**Comment by bezin** [comment] 2017-09-26 13:52
Not necessarily🍾 I just found out, that the response includes the display order for every merge field  (http://developer.mailchimp.com/documentation/mailchimp/reference/lists/merge-fields/#read-get_lists_list_id_merge_fields). 

The email field is not included though, but if we have e.g. three fields (first name, last name, email) and the following display order, we may guess its position: 

1 for first_name and 2 for last_name, email must be the last. 
2 for first_name and 3 for last_name, email must be the first.
1 for first_name and 3 for last_name, email must be second.

**Comment by bastibuck** [comment] 2017-09-26 14:19
As long as **display order** always gives a consecutive order it should be possible to find the email field's position with your solution easily. Like the idea! 

> we may guess its position


It's not even _guessing_, it's more like _finding_ - absolutely fine with finding a position ;)

**Comment by bezin** [comment] 2017-09-26 14:23
I'll try it again with some more fields, to check if it is "always" in consecutive order. With the given orders above that was the case.

**Comment by bezin** [comment] 2017-09-26 15:03
I tried it with up to seven fields – it works as expected. The display_order field is always in a consecutive order, the place of the email field left out. I am gonna fork it and create a PR for this :)

**Comment by bytehead** [comment] 2017-09-26 15:04
Thank you in advance! 👍

**Comment by bastibuck** [comment] 2017-09-26 17:59
Thanks :-)

**Comment by bytehead** [comment] 2017-09-27 07:20
I'll close this in favor of #7, thanks to you guys!

**Closed as completed by bytehead** 2017-09-27 07:20 UTC
Labels: enhancement

**Comment by bezin** [comment] 2017-09-27 07:56
Thanks for the quick merge. I was just gonna say we could make this backwards compatible, but anyway, it is a small extension, the upgrade should be quite easy ;)

**Comment by bytehead** [comment] 2017-09-27 09:56
You're welcome. Yeah, we could have make this BC, but it's not worth the effort anyway 😄

**Comment by bytehead** [comment] 2017-10-03 16:30
3.0.0 contains a nasty bug, subscribe won't work. Update to 3.0.1.
